# Diverse Classroom 

_Questions:_

-  How can I prepare for effective co-teaching?
-  What are the challenges of managing a heterogeneous classroom?
- What do I do if there is a Code of Conduct violation?

_Objectives:_

- Evaluate different strategies for managing a class in which learners have diverse backgrounds and skill levels.
- Know what to do if someone at your workshop violates the Code of Conduct.



## Managing a Diverse Classroom
  
Diverse backgrounds and technical levels. - _It is a challenge_

### Exercise: What Are the Challenges?  
10 min. What are some of the challenges you might expect when teaching learners with a broad range of expertise? Discuss with a partner and put your thoughts in the Etherpad.

## Never Teach Alone: How to Be a Co-instructor

- Team teaching one stream 
- Teaching assitant interchange

[Lateral Knowledge transfer](https://www.open.edu/openlearn/ocw/pluginfile.php/1165520/mod_oucontent/oucontent/59804/4fb93dd4/c64bcb75/ar1_wk4_fig4.tif.jpg===)