# Welcome

Over the last hundred years, researchers have discovered an enormous amount about how people learn and how best to teach them. Unfortunately, much of that knowledge has not yet been translated into classroom practice at the university level.

Over the next two days we will - through short bursts of theory and lots of exercises:

- Introduce you to evidence-based best-practices of teaching.
- Teach you how to create a positive environment in your workshops.
- Provide opportunities for you to practice and build your teaching skills.
- Help you become understand what it is and integrate into the Carpentries community.
- Prepare you to use these teaching skills in teaching workshops.

What we won’t be learning:

- How to code
- How to develop lessons (although ask me)

Those who complete the two full days and some short follow-up exercises/activities online will be certified to teach Carpentry workshops.

## Active learning

Learners who actively engage with course materials will end up retaining it for much longer than they would have otherwise, and they will be better able to apply their knowledge broadly. - _Waldrop, Nature 2015_

[Active learning examples](https://www.everettcc.edu/files/administration/institutional-effectiveness/institutional-research/outcomeassess-active-learning.pdf){:target="_blank"}

## Concept maps

emphasis on relationships between concepts, and multiple parents per node

### Activity read
[Concept maps vs mind maps characteristics](https://www.nngroup.com/articles/cognitive-mind-concept/) and [video](https://www.nngroup.com/videos/visual-mapping-strategies/)

### Exercise 

10 min. Draw a concept map of your topic to teach, start with a question 
Include 7 (+ - 4) concepts
Include relationships as action verbs between these concepts
Arrange it in a hierarchical structure with the key concepts on top.

### Exercise 

8 min. In a group of 3 exchange concept maps. Do not explain the map.
- Write one thing you are confused/not sure about the map
- Write one thing you like/it is clear about the map 
- Each person will give and receive two feedbacks: Positive and Negative on content 



## Guided practice

[Coding exercises](http://third-bit.com/2017/10/16/exercise-types.html) from Greg Wilson 

### (Alternative) Activity 

Check the kinds of exercises and list which ones are represented in the previous example.

_Find any empty files starting from the current directory and looking in its subfolders._

  `find -type f . -empty
  find -r . -type f -empty
  find . -type -empty
  find . -type f -empty`



