## Mindset- 30 minutes

 Questions

    How does mindset influence learning?
    How should we praise our learners?
    How should we talk about errors?
    What are successful habits of lifelong learners?


Carol Dweck discovered that, in any given area, people tend to have either a fixed mindset - believing that someone’s ability in that area is intrinsic, you’re either born with it or you’re not - or a growth mindset - believing that, with enough effort, almost anyone can learn almost anything. 

Do you believe that you’re just not good at math? Or maybe you’re not artistic? Not good at sports? If any of these sound like you, you probably have a fixed mindset when it comes to mathematical, artistic and/or athletic ability.

People with a fixed mindset tend to avoid effort and to give up when faced with failure or challenge. They also tend to take fewer risks, be less likely to take an opportunity to learn something new and to feel best about themselves when they perform flawlessly. In contrast, people with a growth mindset tend to actively seek challenges and to work harder when faced with failure. They regularly take risks and take advantage of opportunities for learning new skills. In fact, initial difficulties in a topic make them more interested and motivated to learn!


## Exercise
Think: What kind of mindset do you have about different areas? Is there anything you believe you are “not naturally talented” at? Mindset often varies in different areas – someone might have a fixed mindset with respect to artistic ability, but a growth mindset with respect to computing skill. Then, think about your learners. How might a learner’s mindset about computational skill influence their learning in a workshop setting?

Pair: Discuss your thoughts about the influence of mindset in a workshop. Try to come up with a few different ways or situations in which mindset might be relevant.

Share: A few thoughts in the Etherpad (or go around the room and discuss)

This exercise should take about 5 minutes.

## Praise Influences Mindset - 2min
There are 3 types of praise:

- performance-based, 
- effort-based 
- improvement-based


## Explain
We’re most used to hearing **performance-based** praise. This sort of praise focuses on outcomes and implies that the outcome (for example, getting a correct answer) is the most important part of the task. It is often (but not always) combined with language that explicitly or implicitly supports the “intrinsic” model of competence. For example, “You did a great job! You must be very smart.”

**Effort-based praise** focuses on the learner’s hard work. For example, “You did a good job, you must have worked very hard.” Exposing learners frequently to this type of praise helps them to transition from a fixed mindset to a growth mindset by changing their perception of effort. For fixed-mindset people, if something doesn’t come easy to you, it means that you don’t have natural ability and shouldn’t bother. People with a growth mindset are much more likely to persevere in the face of challenge and accomplish their goals.

**Improvement-based praise** is related to praise based on effort, but explicitly draws a learner’s attention to the progress they’ve made. For example, “You’re doing so much better at this than last time, you must have worked very hard.” This helps reinforce a growth-mindset by highlighting our ability to improve with effort.


## Exercise 2
Since we’re so used to being praised for our performance, it can be challenging to change the way we praise our learners. Which of these are examples of performance-based, effort-based, or improvement-based praise?

    I like the way you tried a couple of different strategies to solve that problem.
    You’re getting really good at that. Keep up the hard work!
    You’re really talented.
    That was a hard problem. You didn’t get the right answer, but look at how much you learned trying to solve it!



    Effort-based.
    Improvement-based.
    Performance-based.
    Improvement-based.
    
    
## Recovering from errors is essential to learning

Positive error framing is the process of presenting errors as an integral part of the learning process and using them as teaching opportunities. Error framing encourages learners to understand that making errors provides valuable learning opportunities instead of having negative consequences

Important for language learning! 


## Lifelong learning

Both grit and curiosity have been identified as success factors in lifelong learning.
