# Welcome

Over the last hundred years, researchers have discovered an enormous amount about how people learn and how best to teach them. Unfortunately, much of that knowledge has not yet been translated into classroom practice at the university level.

Over the next two days we will - through short bursts of theory and lots of exercises:

- Introduce you to evidence-based best-practices of teaching.
- Teach you how to create a positive environment in your workshops.
- Provide opportunities for you to practice and build your teaching skills.
- Help you become understand what it is and integrate into the Carpentries community.
- Prepare you to use these teaching skills in teaching workshops.

What we won’t be learning:

- How to code
- How to develop lessons (although ask me)

Those who complete the two full days and some short follow-up exercises/activities online will be certified to teach Carpentry workshops.


### Activity 1
- In the Etherpad, write down your name, the best class you ever took (or one class from your top ten, if you can’t decide), and what made it so great. This exercise should take about 2 minutes.


### (Alternative) Activity 1 (while you wait?) - Something Surprising

- Find someone who shares something surprising with you (e.g. your pet has the same name, or you both brush your teeth in the shower). Put your “surprise” similarity into the Etherpad when you come back from break and vote on the most surprising.


