# Welcome - 25 min

### (Alternative) Activity 1 (while you wait?) - Something Surprising

- Find someone who shares something surprising with you (e.g. your pet has the same name, or you both brush your teeth in the shower). Put your “surprise” similarity into the Etherpad when we start and vote on the most surprising (using + signs!).



### Introductions

Darya: 

- Bioinformatics, Genomics - UQ  
- Ex biochemist, Russian sob story
- Data Science Educator and Data Scientist
- Grad Cert High Ed, Developer, GTA/
- Maintainer, Mentor, Trainer, Community organiser
- Why am I passionate about teaching? Why am I an instructor?


- Software Carpentry, Data Carpentry, and Library Carpentry are official Lesson Programs of the Carpentries.

- Software Carpentry focuses on helping researchers develop foundational computational skills
- Data Carpentry focuses on helping researchers work effectively with their data through its lifecycle
- Library Carpentry focuses on teaching data skills to people working in library- and information-related roles.

## The expectation of instructors (and what we'll try to help with)


- "How Learning Works": understand how to apply research-based teaching principles as they apply to the Carpentries audience.
- practice and develop skills in the teaching methods used in workshops
- understand the importance of a respectful and inclusive classroom environment; commit to creating such an environment; and be able to identify and implement Carpentries policies and general practices to accomplish this. Mention CoC here. 
- learn enough about the Carpentries to know where to go for help, how to start organizing a workshop, and how to get involved with community activities.


Over the next two days we will - through short bursts of theory and lots of exercises we will work on a lot of these, but:

What we won’t be learning:

- How to code
- How to develop lessons (although ask me)

Those who complete the two full days and some short follow-up exercises/activities online will be certified to teach Carpentry workshops.

 We welcome questions and dialogue at any point. We’ll be using the Etherpad to help facilitate discussion. Please feel free to ask questions verbally or to put them into the notes or chat box of the Etherpad.

### Activity 1
- In the Etherpad, write down your name, the best class you ever took (or one class from your top ten, if you can’t decide), and what made it so great. This exercise should take about 2 minutes.





***





