# Workshop intros - 40

    Think back to courses or workshops you really liked or didn’t like.

1. How did those courses start?
2. Were you confident in the instructors abilities?
3. Did you feel like they were enthusiastic about the course and invested in you?
4. Was it clear what you were going to be learning?
5. Were you excited about the material?
6. Did you leave that first day thinking the instructor was uninterested, that you weren’t the learners they wanted to be teaching or you had no idea what the course was supposed to be about?

Your impression on the first day of a course probably matched that of the rest of the course. Introductions set the tone for the workshop and the path for learning.

Introductions are particularly important when we have just two days. Also, in Carpentry workshops we’re teaching not only a set of skills, but also trying to give learners the confidence to become self-directed learners. Learners should leave feeling excited and empowered. It’s up to you as an instructor to empower your learners, so it’s important to set a positive and welcoming environment for the workshop.

Having a planned introduction, also helps you be less nervous. Having a planned introduction helps get you started. Even in the face of early technical issues (which is common at the start of a workshop), you can have a chance to reset with something you’re comfortable and ready for.

## Activity
Get into small groups (3-4 people) and discuss these questions for 10 minutes. Take notes on your answers – we’ll combine them later.

    What do you hope to accomplish in a workshop introduction?
    What information do you need to include in an introduction to accomplish these goals?

After 5 minutes, come together, and combine ideas as a large group.


## Goals For the Introduction

After the introduction learners should:

    believe in your competence to teach the workshop
    be able to predict the type of instruction
    know what will be taught
    know what will be required of them

The instructor should:

    have an understanding of who is taking the workshop and what their expectations are
    
    
## To meet these objectives an introduction should:

1. Set positive first impressions
  - attire
  - first impressions: not late, welcoming
  - physical space: rows, groups etc

2. Introduce yourself effectively (and have other workshop leaders do the same)

What characteristics do you want to convey about yourself? You probably want the learners to get a sense of your qualifications, how formal/informal you want to be, and how available you will be to the learners. You want to demonstrate that you’re qualified, but that you share the same challenges as the learners, so you remain accessible.

What will you need to say to convey those characteristics? Consider talking about your research and computational interests as they relate to the workshop, in order to establish yourself as an authority, and to make the workshop more relevant.

Why are you teaching a Carpentries workshop? Why are you an instructor? What’s motivating you to be there today? One reason might be that you took a workshop and saw how valuable these skills were in your own work and wanted to share this information with others. Convey your enthusiasm for being there.

What should you be careful not to say? Learners do not need to know everything about you. In particular, it is not helpful to say you’ve never taught the course before, or that it is your least favorite course to teach, or to disclose any irrelevant personal information that can undermine you in the eyes of your learners.


3. Clarify learning objectives and expectations


Describe the prerequisites so learners will know what information you are assuming they already know. For Data Carpentry no prior computational experience is required. Expectations vary for Software Carpentry and Library Carpentry workshops. Convey what your expectations are.

Highlight main aspects of the schedule.

Communicate the workshop structure so the learners will understand the decisions that have been made in designing the workshop. Make sure to highlight the learning objectives and the hands-on instructional strategies we use and the workshop policies.

Clarify workshop roles. Explain who is doing what at the workshop and what learners can expect from the workshop leaders. If you haven’t already introduced helpers or other workshop leaders, make sure to do so.

Explain your expectations for learner behavior including expectations around:

    Code of Conduct
    ways to ask for help
    ways to give instructors feedback

Communicate your commitment to the learners’ learning experience.

Share some advice for success in your course. Let learners know you are confident in their success as long as they put in the required effort.


4. Help learners learn about each other
5. Set the tone for the workshop
  - Since these workshops are hands-on don’t spend a lot of the time at the beginning lecturing. 
  - get to group work and activities quickly
  
6. Collect baseline data on learners’ knowledge and motivation
  - Survey: use it!
  
7. Whet learners’ appetite for workshop content
8. Inform Learners of Logistics

## Activity

Practice Your Introduction

Imagine you have completed instructor training and you are about to teach a full lesson around the material you have been practicing teaching today.

    Write out some notes, covering some of the topics described above:
        Introduce yourself effectively
        Clarify learning objectives and expectations
        Set the tone for the workshop
    Return to your groups of 2 or 3 and each give 2 minutes of your introduction. (5-6 min)
    After each introduction, provide 2-3 minutes of feedback.

