## Wrap up and HW

Today we have focused on understanding some core findings of pedagogical research about how the learning process works and the importance of creating a positive classroom environment. We also introduced the idea of lesson study and gave some opportunities to practice teaching. Tomorrow we will continue our discussions of how we build teaching skill and will have more chances for practice and feedback. We will also look in some depth at how the Carpentries operate to prepare you for the logistics of teaching a workshop.


To prepare for tomorrow, please:

1. Read about the two types of Carpentry workshops: self-organized and centrally-organized and the checklists these pages link to. These summarize commonly asked questions about organizing and running workshops. When you arrive tomorrow, we will ask you to add one question about our operations to a list. We will then do our best to answer all of those questions during the day.

2.Prepare for the live coding exercises. 

***

3. Finally: provide feedback

1. What is one thing we could have done as instructors to make todays lessons more effective?

2. What thing did you find most confusing about today?

4. Self reflection - 10 min


Before we wrap up for the day, take 5 minutes to think over everything we covered today.  On a piece of paper, write down something that captures what you want to remember about the day.  The Trainers won’t look at this - it’s just for you.
  
If you don’t know where to start, consider the following list for a starting point:
  

    draw a concept map, connecting the material

    draw pictures or a comic depicting one of the day’s concepts

    write an outline of the topics we covered

    write a paragraph or “journal” entry about your experience of the training today

    write down one thing that struck you the most

  
This exercise should take about 10 minutes.